### ISSUE TITLE
html_tag(): undefined method `options' for nil:NilClass when having application.html.slim instead of haml

### ISSUE THREAD

**Issue by jmuheim** [sporkd/html5-rails#26]
My SLIM file:

``` slim
doctype html
- html_tag class: "no-js" do # Adds IE-specific CSS classes
  = render "head"

  body class=controller.controller_name
    = render "chromeframe"
    = render "header"

    #main role="main"
      = render "flashes"
      = yield

    = render "footer"

    -# Javascript at the bottom for fast page loading
    = render "javascripts"
```

Output when loading page:

```
undefined method `options' for nil:NilClass

#<Class:0x007fd985f61bc8>#_app_views_layouts_application_html_slim__2652867622890682822_70286116180140
app/views/layouts/application.html.slim, line 2
```

Any help on that? Before when I used HAML this worked perfectly.

**Comment by errm** [comment]
Could you update the gem and try again?

**Comment by sporkd** [comment]
The html_tag helper is not compatible with slim because it lacks the ability to do something like `slim_concat`. See https://groups.google.com/forum/#!msg/slim-template/7gbG1wzDxAs/C06ivayJe20J

There might be a way to make it work, but I couldn't figure it out. However, adding the slim-rails gem to your gemfile will now generate a working slim layout with inline html tags.
