### ISSUE TITLE
What's "app/assets/stylesheets/application/document.css.scss" intended use?

### ISSUE THREAD

**Issue by jmuheim** [sporkd/html5-rails#29]
I'm a bit unsure what's the intended use of `app/assets/stylesheets/application/document.css.scss`. Is it a place for the app's styles? Shouldn't they be place in individual `resources_name.css` files (e.g. `users.css`)? Or is it meant for application-wide styles (instead of messing up `application.css`)?

Thanks a lot for informations.

**Comment by sporkd** [comment]
It depends. I don't typically like to break up my css by resource because there's typically lots of sharing between resources. The idea was more that each directory under stylesheets is a different section of the site (i.e. application vs admin).  So everything inside of the default application directory might be for your main user facing app.  Of course you could add additional resource based scss files inside application.  It's meant to be more of a guideline and not necessarily a hard requirement.  Hope that helps.

**Comment by sporkd** [comment]
BTW, to create a new section (like an admin section) you could run the following:

```
  rails generate html5:layout admin
  rails generate html5:assets admin
```

**Comment by jmuheim** [comment]
Okay, thanks for explaining this. :+1:
